/**
 * AI 기반 일정 추출 어댑터 — 입력 raw payload → CalendarEvent.
 *
 * 현재 단계는 OpenAI API를 호출하지 않고 규칙 기반(혹은 빈 값) 추출만
 * 수행합니다. 후속 단계에서 OpenAI 또는 다른 LLM으로 교체할 때
 * 입력/출력 타입을 유지하면 호출부 변경 없이 그대로 사용 가능합니다.
 *
 * AI 역할 (허용):
 *  - 날짜 추출
 *  - 종목명 / 티커 추출
 *  - 일정 유형(category) 분류
 *  - 제목 / 짧은 설명 생성
 *  - 확인할 항목 목록 생성
 *
 * AI 역할 (금지):
 *  - 현재가 / 실적 수치 임의 생성
 *  - 투자 판단 / 매수·매도 신호 / 추천·비추천
 */

import type {
  CalendarCategory,
  CalendarEvent,
  CalendarMarket,
  CalendarSourceType,
} from "@/lib/calendar/types";

interface RawDisclosure {
  rcept_no?: string;
  report_nm?: string;
  rcept_dt?: string; // yyyymmdd
  corp_name?: string;
  stock_code?: string;
}

interface RawSecFiling {
  accession?: string;
  form?: string;
  filingDate?: string; // yyyy-mm-dd
  reportDate?: string;
  ticker?: string;
  company?: string;
  url?: string;
}

interface RawNewsItem {
  title?: string;
  publisher?: string;
  publishedAt?: string;
  url?: string;
  ticker?: string;
  market?: CalendarMarket;
}

interface RawEarnings {
  symbol?: string;
  company?: string;
  market?: CalendarMarket;
  expectedDate?: string;
  period?: string;
}

interface RawEconomicIndicator {
  title?: string;
  date?: string;
  market?: CalendarMarket;
  region?: string;
}

function ts() {
  return new Date().toISOString();
}

function fromYyyymmdd(s?: string): string | null {
  if (!s || s.length !== 8) return null;
  return `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}`;
}

function classifyDisclosure(reportNm: string): CalendarCategory {
  if (/배당/.test(reportNm)) return "dividend";
  if (/주주총회/.test(reportNm)) return "shareholder_meeting";
  if (/사업보고서|반기보고서|분기보고서|실적/.test(reportNm)) return "earnings";
  return "filing";
}

function classifySecForm(form: string): CalendarCategory {
  if (form === "10-K" || form === "10-Q" || form === "8-K") return "filing";
  if (form === "DEF 14A") return "shareholder_meeting";
  return "filing";
}

export function parseDisclosureToCalendarEvent(
  raw: RawDisclosure,
): CalendarEvent | null {
  const date = fromYyyymmdd(raw.rcept_dt);
  const title = raw.report_nm?.trim();
  if (!date || !title) return null;
  const category = classifyDisclosure(title);
  return {
    id: `dart-${raw.rcept_no ?? Math.random().toString(36).slice(2)}`,
    date,
    title,
    category,
    market: "kr",
    companyName: raw.corp_name,
    symbol: raw.stock_code,
    description: `${raw.corp_name ?? "회사"} 관련 공시 일정입니다. 자세한 내용은 원문에서 확인할 수 있습니다.`,
    checkpoints: ["원문 확인 필요", "구체 금액·기간·대상"],
    sourceLabel: "OpenDART",
    sourceUrl: raw.rcept_no
      ? `https://dart.fss.or.kr/dsaf001/main.do?rcpNo=${raw.rcept_no}`
      : undefined,
    sourceType: "opendart" satisfies CalendarSourceType,
    createdAt: ts(),
    updatedAt: ts(),
    detectedAt: ts(),
    lastRefreshedAt: ts(),
    confidence: 0.95,
    isAutoGenerated: true,
  };
}

export function parseSecFilingToCalendarEvent(
  raw: RawSecFiling,
): CalendarEvent | null {
  if (!raw.filingDate || !raw.form) return null;
  return {
    id: `sec-${raw.accession ?? Math.random().toString(36).slice(2)}`,
    date: raw.filingDate,
    title: `${raw.company ?? raw.ticker ?? "Company"} ${raw.form}`,
    category: classifySecForm(raw.form),
    market: "us",
    companyName: raw.company,
    symbol: raw.ticker,
    description: `${raw.company ?? raw.ticker ?? "Company"}의 ${raw.form} 제출 일정입니다.`,
    checkpoints: ["원문 확인 필요", "MD&A 코멘트", "세그먼트 매출 흐름"],
    sourceLabel: "SEC EDGAR",
    sourceUrl: raw.url,
    sourceType: "sec",
    createdAt: ts(),
    updatedAt: ts(),
    detectedAt: ts(),
    lastRefreshedAt: ts(),
    confidence: 0.95,
    isAutoGenerated: true,
  };
}

export function parseNewsToCalendarEvent(
  raw: RawNewsItem,
): CalendarEvent | null {
  if (!raw.title || !raw.publishedAt) return null;
  const date = raw.publishedAt.slice(0, 10);
  return {
    id: `news-${date}-${raw.title.slice(0, 16)}`,
    date,
    title: raw.title,
    category: "news",
    market: raw.market ?? "global",
    symbol: raw.ticker,
    description: `${raw.publisher ?? "주요 언론사"} 보도. 정리된 정보 흐름을 확인할 수 있는 일정입니다.`,
    checkpoints: ["원문 확인 필요"],
    sourceLabel: raw.publisher ?? "주요 언론사 보도",
    sourceUrl: raw.url,
    sourceType: "news",
    createdAt: ts(),
    updatedAt: ts(),
    detectedAt: ts(),
    lastRefreshedAt: ts(),
    confidence: 0.7,
    isAutoGenerated: true,
  };
}

export function parseEarningsDataToCalendarEvent(
  raw: RawEarnings,
): CalendarEvent | null {
  if (!raw.expectedDate || !raw.symbol) return null;
  return {
    id: `earnings-${raw.symbol}-${raw.expectedDate}`,
    date: raw.expectedDate,
    title: `${raw.company ?? raw.symbol} 분기 실적 발표`,
    category: "earnings",
    market: raw.market ?? (/^[0-9]{6}$/.test(raw.symbol) ? "kr" : "us"),
    companyName: raw.company,
    symbol: raw.symbol,
    description: `${raw.company ?? raw.symbol}의 ${raw.period ?? "분기"} 실적 발표 일정입니다.`,
    checkpoints: [
      "매출 / 영업이익 / 순이익",
      "사업부문별 흐름",
      "다음 분기 가이던스 변화",
    ],
    sourceLabel: "Earnings Calendar",
    sourceType: "earnings_calendar",
    createdAt: ts(),
    updatedAt: ts(),
    detectedAt: ts(),
    lastRefreshedAt: ts(),
    confidence: 0.8,
    isAutoGenerated: true,
  };
}

export function parseEconomicIndicatorToCalendarEvent(
  raw: RawEconomicIndicator,
): CalendarEvent | null {
  if (!raw.title || !raw.date) return null;
  return {
    id: `econ-${raw.date}-${raw.title.slice(0, 16)}`,
    date: raw.date,
    title: raw.title,
    category: "economic",
    market: raw.market ?? "global",
    description: `${raw.title} 발표 일정입니다. 시장 반응은 발표 직후 함께 확인할 수 있습니다.`,
    checkpoints: ["헤드라인 수치", "예상치 대비", "시장 반응"],
    sourceLabel: "경제지표 캘린더",
    sourceType: "economic_calendar",
    createdAt: ts(),
    updatedAt: ts(),
    detectedAt: ts(),
    lastRefreshedAt: ts(),
    confidence: 0.9,
    isAutoGenerated: true,
  };
}
