/**
 * 월간 캘린더 샘플 일정 생성기.
 *
 * 특정 월에 고정되지 않고 (year, month)를 받아 그 월에 맞춰
 * 결정론적으로 20개 이상의 이벤트를 생성합니다. 시드는 (year*12+month)
 * 기반이라 같은 월 = 같은 결과 + 다른 월 = 다른 결과.
 *
 * 추후 단계에서 OpenDART / SEC / 뉴스 / 실적 / 경제지표 / OpenAI 정리 결과로
 * 교체할 때 동일한 CalendarEvent 형태로 채워 넣으면 화면 코드는 그대로
 * 동작합니다.
 */

import {
  getMonthDays,
  toIsoDate,
} from "@/lib/calendar/dateUtils";
import type {
  CalendarCategory,
  CalendarEvent,
  CalendarMarket,
  CalendarSourceType,
} from "@/lib/calendar/types";

// -------- helpers --------

function makeRng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

function pick<T>(rng: () => number, arr: T[]): T {
  return arr[Math.floor(rng() * arr.length) % arr.length];
}

function nDaysAgoIso(daysAgo: number, now: Date = new Date()): string {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(8 + (daysAgo % 9), (daysAgo * 7) % 60, 0, 0);
  return d.toISOString();
}

// -------- catalogs --------

interface CompanyHint {
  name: string;
  symbol: string;
  market: "kr" | "us";
}

const KR_COMPANIES: CompanyHint[] = [
  { name: "삼성전자", symbol: "005930", market: "kr" },
  { name: "SK하이닉스", symbol: "000660", market: "kr" },
  { name: "NAVER", symbol: "035420", market: "kr" },
  { name: "카카오", symbol: "035720", market: "kr" },
  { name: "현대차", symbol: "005380", market: "kr" },
  { name: "기아", symbol: "000270", market: "kr" },
  { name: "셀트리온", symbol: "068270", market: "kr" },
  { name: "한화에어로스페이스", symbol: "012450", market: "kr" },
  { name: "두산에너빌리티", symbol: "034020", market: "kr" },
  { name: "LG에너지솔루션", symbol: "373220", market: "kr" },
];

const US_COMPANIES: CompanyHint[] = [
  { name: "Apple", symbol: "AAPL", market: "us" },
  { name: "Microsoft", symbol: "MSFT", market: "us" },
  { name: "Nvidia", symbol: "NVDA", market: "us" },
  { name: "Tesla", symbol: "TSLA", market: "us" },
  { name: "Palantir", symbol: "PLTR", market: "us" },
  { name: "Alphabet", symbol: "GOOGL", market: "us" },
  { name: "Amazon", symbol: "AMZN", market: "us" },
  { name: "Meta", symbol: "META", market: "us" },
  { name: "AMD", symbol: "AMD", market: "us" },
];

const ECONOMIC_INDICATORS = [
  {
    title: "미국 소비자물가지수(CPI) 발표",
    market: "us" as CalendarMarket,
    checkpoints: ["헤드라인·코어 전월 대비", "에너지 항목 영향", "주거비 흐름"],
  },
  {
    title: "FOMC 의사록 공개",
    market: "us" as CalendarMarket,
    checkpoints: ["금리 인상/인하 가이드 변화", "양적 긴축 일정", "위원별 의견"],
  },
  {
    title: "미국 5월 비농업 고용지표",
    market: "us" as CalendarMarket,
    checkpoints: ["고용 증가 폭", "실업률", "임금 상승률"],
  },
  {
    title: "한국 기준금리 발표",
    market: "kr" as CalendarMarket,
    checkpoints: ["금리 결정 결과", "총재 회의 발언", "수정 경제전망"],
  },
  {
    title: "한국 소비자심리지수 발표",
    market: "kr" as CalendarMarket,
    checkpoints: ["전월 대비 변동", "세부 지수 흐름"],
  },
  {
    title: "한국 무역수지·수출입 동향",
    market: "kr" as CalendarMarket,
    checkpoints: ["반도체·자동차 수출", "대중·대미 교역", "전월 대비 변화"],
  },
  {
    title: "글로벌 5월 제조업 PMI",
    market: "global" as CalendarMarket,
    checkpoints: ["한국·미국·유럽 PMI", "신규 주문 흐름", "재고 사이클"],
  },
];

const NEWS_TITLES = [
  "주요 업종 외국인 매매 동향 정리",
  "반도체 업황 관련 시장 코멘트 모음",
  "전기차 시장 주요 이슈 정리",
  "미국 빅테크 AI 인프라 투자 관련 보도 모음",
  "환율·금리 변화 관련 시장 관측 정리",
];

// -------- builder --------

function eventId(year: number, month: number, idx: number): string {
  return `cal-${year}${String(month).padStart(2, "0")}-${idx.toString(36)}`;
}

interface BuildOptions {
  /** 데모용 detectedAt 기준 시각 (테스트에서 고정값 주입 가능) */
  now?: Date;
}

export function generateMonthlyCalendar(
  year: number,
  month: number,
  options: BuildOptions = {},
): CalendarEvent[] {
  const now = options.now ?? new Date();
  const rng = makeRng(year * 12 + month);
  const monthDays = getMonthDays(year, month);

  const events: CalendarEvent[] = [];

  // helper to push
  const push = (
    day: number,
    base: Omit<CalendarEvent, "id" | "date" | "createdAt" | "updatedAt">,
  ) => {
    const safeDay = ((day - 1) % monthDays) + 1;
    const date = toIsoDate(new Date(year, month - 1, safeDay));
    const detectedDaysAgo = Math.floor(rng() * 7);
    events.push({
      id: eventId(year, month, events.length),
      date,
      createdAt: nDaysAgoIso(detectedDaysAgo + 1, now),
      updatedAt: nDaysAgoIso(detectedDaysAgo, now),
      detectedAt: nDaysAgoIso(detectedDaysAgo, now),
      lastRefreshedAt: nDaysAgoIso(Math.max(0, detectedDaysAgo - 1), now),
      isAutoGenerated: true,
      confidence: 0.7 + rng() * 0.3,
      ...base,
    });
  };

  // ---- 한국 실적 (~5건) ----
  for (let i = 0; i < 5; i++) {
    const c = KR_COMPANIES[Math.floor(rng() * KR_COMPANIES.length)];
    const day = Math.floor(2 + rng() * (monthDays - 3));
    push(day, {
      title: `${c.name} 분기 실적 발표`,
      category: "earnings",
      market: "kr",
      companyName: c.name,
      symbol: c.symbol,
      description: `${c.name}의 분기 매출·영업이익·순이익이 공개되는 일정입니다. 자세한 수치는 발표 자료를 통해 확인할 수 있습니다.`,
      checkpoints: [
        "매출·영업이익·순이익",
        "사업부문별 실적 흐름",
        "환율 및 일회성 비용 영향",
      ],
      sourceLabel: "기업 IR",
      sourceUrl: "#",
      sourceType: "earnings_calendar" satisfies CalendarSourceType,
    });
  }

  // ---- 미국 실적 (~5건) ----
  for (let i = 0; i < 5; i++) {
    const c = US_COMPANIES[Math.floor(rng() * US_COMPANIES.length)];
    const day = Math.floor(2 + rng() * (monthDays - 3));
    push(day, {
      title: `${c.name} 분기 실적 발표`,
      category: "earnings",
      market: "us",
      companyName: c.name,
      symbol: c.symbol,
      description: `${c.name}의 분기 매출·영업이익·EPS가 공개되는 일정입니다. 컨퍼런스콜에서 가이던스 변경 여부도 함께 확인할 수 있습니다.`,
      checkpoints: [
        "매출 / 영업이익 / EPS",
        "세그먼트별 매출 흐름",
        "다음 분기 가이던스 변화",
      ],
      sourceLabel: "Earnings Call",
      sourceUrl: "#",
      sourceType: "earnings_calendar",
    });
  }

  // ---- 한국 공시 (~3건) ----
  const krDisclosures = [
    {
      title: "DART 정기보고서 마감 (분기보고서)",
      checkpoints: [
        "분기보고서 제출 일정",
        "사업부문별 매출/이익 정리",
        "주주 구성 변화",
      ],
    },
    {
      title: "주요사항보고서 검토 (자기주식 관련)",
      checkpoints: ["취득/처분 규모", "기간 및 목적", "기존 자사주 보유 현황"],
    },
    {
      title: "감사보고서 제출 마감",
      checkpoints: ["감사의견", "주석 사항", "내부회계관리제도"],
    },
  ];
  krDisclosures.forEach((d, i) => {
    const day = 8 + i * 6 + Math.floor(rng() * 3);
    push(day, {
      title: d.title,
      category: "filing",
      market: "kr",
      description: `${d.title} 관련 일정입니다. 자세한 내용은 DART 공시 원문에서 확인할 수 있습니다.`,
      checkpoints: d.checkpoints,
      sourceLabel: "OpenDART",
      sourceUrl: "#",
      sourceType: "opendart",
    });
  });

  // ---- 미국 공시 (~2건) ----
  const usDisclosures = [
    {
      title: "SEC 10-Q 제출 시즌",
      checkpoints: ["MD&A 코멘트", "세그먼트 매출", "Cash Flow"],
    },
    {
      title: "13F 보유내역 공시 마감",
      checkpoints: [
        "헤지펀드 주요 매수/매도",
        "테크 비중 변화",
        "신규 진입 종목 목록",
      ],
    },
  ];
  usDisclosures.forEach((d, i) => {
    const day = 14 + i * 6 + Math.floor(rng() * 3);
    push(day, {
      title: d.title,
      category: "filing",
      market: "us",
      description: `${d.title} 관련 일정입니다. SEC EDGAR에서 원문을 직접 확인할 수 있습니다.`,
      checkpoints: d.checkpoints,
      sourceLabel: "SEC EDGAR",
      sourceUrl: "#",
      sourceType: "sec",
    });
  });

  // ---- 경제지표 (~5건) ----
  for (let i = 0; i < 5; i++) {
    const ind = ECONOMIC_INDICATORS[i % ECONOMIC_INDICATORS.length];
    const day = 3 + i * 5 + Math.floor(rng() * 3);
    push(day, {
      title: ind.title,
      category: "economic",
      market: ind.market,
      description: `${ind.title} 발표 일정입니다. 발표 직후 시장 반응을 함께 확인할 수 있습니다.`,
      checkpoints: ind.checkpoints,
      sourceLabel: "경제지표 캘린더",
      sourceUrl: "#",
      sourceType: "economic_calendar",
    });
  }

  // ---- 배당 (~2건) ----
  const divDays = [
    Math.floor(monthDays * 0.4),
    Math.floor(monthDays * 0.75),
  ];
  const divCompanies = [
    KR_COMPANIES[0],
    US_COMPANIES[0],
  ];
  divDays.forEach((day, i) => {
    const c = divCompanies[i];
    push(day, {
      title: `${c.name} 배당 기준일`,
      category: "dividend",
      market: c.market,
      companyName: c.name,
      symbol: c.symbol,
      description: `${c.name}의 배당 지급 기준일입니다. 지급 일정과 1주당 배당금은 회사 공시를 함께 확인해 주세요.`,
      checkpoints: ["1주당 배당금", "지급일", "전년 동기 대비 변화"],
      sourceLabel: "배당 공시",
      sourceUrl: "#",
      sourceType: c.market === "kr" ? "opendart" : "sec",
    });
  });

  // ---- 주주총회 (~1~2건) ----
  const meetingDays = [Math.floor(monthDays * 0.6)];
  meetingDays.forEach((day) => {
    const c = KR_COMPANIES[2];
    push(day, {
      title: `${c.name} 주주총회`,
      category: "shareholder_meeting",
      market: "kr",
      companyName: c.name,
      symbol: c.symbol,
      description: `${c.name}의 주주총회 일정입니다. 안건과 의결권 행사 일정은 원문 공시에서 확인할 수 있습니다.`,
      checkpoints: ["주요 안건", "이사 선임", "정관 변경"],
      sourceLabel: "OpenDART",
      sourceUrl: "#",
      sourceType: "opendart",
    });
  });

  // ---- 뉴스성 일정 (~2건) ----
  for (let i = 0; i < 2; i++) {
    const day = Math.floor(2 + rng() * (monthDays - 3));
    push(day, {
      title: pick(rng, NEWS_TITLES),
      category: "news",
      market: pick(rng, ["kr", "us", "global"] as CalendarMarket[]),
      description:
        "정리된 정보 흐름을 데이터 기준으로 한 곳에서 모아 확인할 수 있는 일정입니다.",
      checkpoints: ["주요 키워드", "관련 종목", "후속 코멘트"],
      sourceLabel: "주요 언론사 보도",
      sourceUrl: "#",
      sourceType: "news",
    });
  }

  // ---- 시장 일정 (~1건) ----
  push(monthDays, {
    title: "월말 시장 마감 점검",
    category: "market",
    market: "global",
    description:
      "월말 기준으로 주요 지수 흐름과 업종별 변동을 한 번에 확인할 수 있는 시점입니다.",
    checkpoints: ["KOSPI/KOSDAQ", "S&P 500 / NASDAQ", "환율·금리"],
    sourceLabel: "시장 데이터",
    sourceUrl: "#",
    sourceType: "price",
  });

  // 정렬: 날짜 → 카테고리 순
  events.sort((a, b) =>
    a.date === b.date ? a.category.localeCompare(b.category) : a.date < b.date ? -1 : 1,
  );

  return events;
}
