/**
 * 시장 일정 캘린더 도메인 타입.
 *
 * 현재는 lib/calendar/mockCalendar.ts 가 이 타입을 생성하지만,
 * 나중에 OpenDART/SEC/뉴스/실적/경제지표 API와 OpenAI 정리 단계를 연결할 때도
 * 화면(API 응답) 계약은 이 타입 그대로 유지됩니다.
 */

export type CalendarCategory =
  | "earnings"
  | "filing"
  | "economic"
  | "dividend"
  | "shareholder_meeting"
  | "market"
  | "news";

export type CalendarMarket = "kr" | "us" | "global";

export type CalendarSourceType =
  | "opendart"
  | "sec"
  | "news"
  | "manual"
  | "economic_calendar"
  | "earnings_calendar"
  | "price";

export interface CalendarEvent {
  id: string;
  /** ISO yyyy-mm-dd */
  date: string;
  title: string;
  category: CalendarCategory;
  market: CalendarMarket;
  companyName?: string;
  symbol?: string;
  description: string;
  checkpoints?: string[];
  sourceLabel?: string;
  sourceUrl?: string;
  sourceType?: CalendarSourceType;
  createdAt: string;
  updatedAt: string;
  detectedAt?: string;
  lastRefreshedAt?: string;
  confidence?: number;
  isAutoGenerated?: boolean;
}

export type CalendarRefreshProvider =
  | "opendart"
  | "sec"
  | "news"
  | "earnings"
  | "economic"
  | "price";

export type CalendarRefreshState =
  | "idle"
  | "success"
  | "error"
  | "skipped";

export interface CalendarRefreshStatus {
  provider: CalendarRefreshProvider;
  lastRunAt?: string;
  nextRunAt?: string;
  status: CalendarRefreshState;
  message?: string;
}

export interface MonthlySummary {
  total: number;
  byCategory: Record<CalendarCategory, number>;
}

export interface CalendarApiResponse {
  ok: boolean;
  year: number;
  month: number;
  events: CalendarEvent[];
  monthlySummary: MonthlySummary;
  recentlyAddedEvents: CalendarEvent[];
  lastUpdatedAt: string;
  refreshStatus: CalendarRefreshStatus[];
}

/**
 * 사용자 화면용 라벨 매핑.
 * 내부 상태(`success`/`skipped`/`error`/`idle`)는 사용자에게 그대로 보여주지 않고
 * 자연스러운 한국어 문구로 변환합니다.
 */
export const REFRESH_STATE_LABEL: Record<CalendarRefreshState, string> = {
  success: "최근 반영 완료",
  skipped: "데이터 기준 유지",
  error: "일부 정보 확인 필요",
  idle: "데이터 기준",
};

export const CATEGORY_LABEL: Record<CalendarCategory, string> = {
  earnings: "실적",
  filing: "공시",
  economic: "경제지표",
  dividend: "배당",
  shareholder_meeting: "주주총회",
  market: "시장",
  news: "뉴스",
};

export const MARKET_LABEL: Record<CalendarMarket, string> = {
  kr: "한국",
  us: "미국",
  global: "글로벌",
};
